# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

[mysql]
host=false
port=false
username=false
password=false
database=false
uri=false
