kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  #name: aks-demo-habitat-operator # Name is case sensitive
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: secret-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-proxy-toml
type: Opaque
data:
  # Each item needs to be base64-encoded.
  # Plain text content:
  #   secret_name="osba-secret"
  user.toml: c2VjcmV0X25hbWU9Im9zYmEtc2VjcmV0Igo=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: wordpress-db-proxy
  labels:
    source: habitat-demo
    app: wordpress-osba-habitat
customVersion: v1beta2
spec:
  v1beta2:
    image: habitatregistry.azurecr.io/azure-habitat-example/osba-mysql-proxy:latest
    count: 1
    service:
      name: osba-mysql-proxy
      topology: standalone
      configSecretName: mysql-proxy-toml
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: wordpress-osba-app
  labels:
    source: habitat-demo
    app: wordpress-osba-habitat
customVersion: v1beta2
spec:
  v1beta2:
    image: habitatregistry.azurecr.io/azure-habitat-example/wordpress:latest
    count: 1
    service:
      name: wordpress
      topology: standalone
      bind:
        - name: database
          service: osba-mysql-proxy
          group: default
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-osba-lb
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    habitat-name: wordpress-osba-app

