apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: habitat-updater
customVersion: v1beta2
spec:
  v1beta2:
    image: habitat/habitat-updater:latest
    count: 1
    service:
      name: habitat-updater
      topology: standalone
